[package]
name = "clatox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
caps = "0.5.5"
nix = "0.26.2"

[dependencies.clatox-netlink]
path = "../clatox-netlink"
version = "0.1.0"
