[package]
name = "rusty-ifinfo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.clatox-rtnetlink]
path = "../clatox-rtnetlink"
version = "0.1.0"
